import os
from typing import List

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_core.prompts import PromptTemplate
from langchain_ollama import ChatOllama
from langchain_openrouter import ChatOpenRouter
from langchain_tavily import TavilySearch
from pydantic import BaseModel, Field
from tavily import TavilyClient

load_dotenv()
os.environ["LANGSMITH_PROJECT"] = "search-agent"
tavily = TavilyClient()


class Source(BaseModel):
    """Schema for a source used by the agent"""

    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """Schema for the agennt response with answer and sources"""

    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(
        default_factory=list, description="List of sources used to generate the answer"
    )


@tool
def search(query: str) -> str:
    """
    Tool that searches over internet
    Args:
        query: The query to search for
    Returns:
        The search results
    """
    print(f"Searching for: {query}")
    return tavily.search(query)


# llm = ChatOpenRouter(temperature=0, model="openrouter/free")
llm = ChatOllama(
    temperature=0,
    model="qwen2.5:latest",
    base_url="http://127.0.0.1:11434",
    num_ctx=16384,  # increae context window since the result of search could be long
    response_format=AgentResponse,  # specify the response format to be AgentResponse
)

agent = create_agent(
    llm, tools=[TavilySearch()]
)  # using langchain_tavily's TavilySearch tool instead of the custom search tool

structured_llm = llm.with_structured_output(AgentResponse)
# split the steps of the agent into structured output with answer and sources because
# otherwise to make the tool call lanngchain will fall back to the default output parser
# This is because the tool call will return a string and the default output parser will not be able to parse it into the AgentResponse model.


def main():
    print("Hello from langchain-course!")

    result = agent.invoke(
        {
            "messages": HumanMessage(
                content="Search for 3 job postings for an ai engineer using langchain in the bay area on linkedin and list their details."
            )
        }
    )

    raw_text_answer = result["messages"][-1].content

    # Format cleanly into your Pydantic structure
    structured_final_response = structured_llm.invoke(
        f"Format this text cleanly into the schema: {raw_text_answer}"
    )

    print(structured_final_response)


if __name__ == "__main__":
    main()
